

export const userData = [
    {
      name: 'Jan',
      "Active Users": 14000,
    },
    {
      name: 'Feb',
      "Active Users": 25000,
    },
    {
      name: 'Mar',
      "Active Users": 50000,
    },
    {
      name: 'Apr',
      "Active Users": 40000,
    },
    {
      name: 'Mai',
      "Active Users": 81000,
    },
    {
      name: 'Jun',
      "Active Users": 100000,
    },
    {
      name: 'Jul',
      "Active Users": 43000,
    },
    {
      name: 'Aug',
      "Active Users": 14000,
    },
    {
      name: 'Sep',
      "Active Users": 52000,
    },
    {
      name: 'Oct',
      "Active Users": 42000,
    },
    {
      name: 'Nov',
      "Active Users": 40000,
    },
    {
      name: 'Dec',
      "Active Users": 52000,
    },
    
  ];

  
  export const userRows = [
    {   id: 1, 
        username: 'email',
        email: 'email@email.com',
        status:'active',
        transaction:'€420.00',
    },
    {   id: 2, 
        username: 'Jonnyboy',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€120.00',
    },
    {   id: 3, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 4, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 5, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 6, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 7, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 8, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 9, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 10, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 11, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 12, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 13, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 14, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 15, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 16, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 17, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 17, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 18, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 19, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 20, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 21, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    {   id: 22, 
        username: 'username10',
        email: 'jdoe@gmail.com',
        status:'active',
        transaction:'€380.00',
    },
    
];

export const productRows = [
  {   id: 1, 
      name: 'Apple Airbook',
      status:'active',
      stock:'400',
      
  },
  {   id: 2, 
      status:'active',
      stock:'400',
      
  },
  {   id: 3, 
      status:'active',
      stock:'1600',
      
  },
  {   id: 4, 
      status:'active',
      stock:'1400',
  },
  {   id: 5, 
      status:'active',
      stock:'1400',
      
  },
  {   id: 6, 
      status:'active',
      stock:'300',
  },
  {   id: 7, 
      status:'active',
      stock:'500',
  },
  {   id: 8, 
      status:'active',
      stock:'200',
  },
  {   id: 9, 
      status:'active',
      stock:'900',
  },
  {   id: 10, 
      status:'active',
      stock:'700',
  },
  {   id: 11, 
      status:'active',
      stock:'500',
  },
  {   id: 12, 
      status:'active',
      stock:'400',
  },
 
];

export const productData = [
    {
      name: 'Jan',
      "Sales": 14000,
    },
    {
      name: 'Feb',
      "Sales": 25000,
    },
    {
      name: 'Mar',
      "Sales": 50000,
    },
    {
      name: 'Apr',
      "Sales": 40000,
    },
];